title: "Valeria's Blog "
description: My blog for the module 'Typographic Design for Page and Screen'.
header_text: Typography that surrounds us
footer_text: Copyright 2020 Your name
header_feature_image: ../uploads/pages.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items: []
