title: Type That Art
description: This blog is going to explore typography as a concept in art and
  how deep of an influence it can have on it and on different art works.
header_text: Typographic Land of Art
footer_text: Copyright 2020 Valeria Ilina
header_feature_image: ../uploads/photo-1540678931042-41a977082abf.jpg
bannerheight: 20vmax
logo: ../uploads/logo-second-option.jpg
favicon: ../uploads/faviconn.ico
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - name: About Me
    siteurl: https://typethatart.netlify.app/aboutme/
    tab: true
